---
title: \vspace{3in} "Visualizing, Modeling, and Forecasting Crashes in Wake County,
  North Carolina"
author:
- Cortlyn Morris, Kelly Wenzlof, Ayan Gulzar
- Faculty Research Mentor Dr. Sayed Mostafa 
- Graduate Research Assistant Mentor Chinedu Jude Nzekwe
date: "7/30/2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes: \usepackage{setspace}\doublespacing
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

# Abstract

Studies have shown that road traffic crashes are one of the leading causes of unnatural death for U.S citizens. In our research, we address three questions about crashes in Wake County, North Carolina: (1) Where are the hot spots for crashes in the Wake County area?; (2) Can we reliably forecast the daily/monthly number of crashes in Wake County? Given the weather and road features and drivers’ characteristics, can we predict the crash outcome (whether it results injuries)? To accomplish this aim, two public data sets covering the period between January 2015 to May 2021 obtained from the North Carolina Wake County Open Data Portal were used (persons involved in crashes and crash locations). We addressed the above research questions using a combination of exploratory data analysis techniques, time series forecasting techniques and predictive modeling techniques. After conducting research we found out that hot spots in Wake County like 440, 40, and Capital Blvd are known to have the most accidents since they are the most common roads. Additionally, we noticed the pandemic is one of the prominent factors that affects crash counts and car crash forecasts, and the best models for forecasting car crashes of the different subgroups of data were TBATS, ARIMA, HoltWinters, and a combination of STLF and SARIMA. Furthermore, we noticed that the best way to model injury types was by applying random forest with a combination of over and undersampling on a subsample and by utilizing logistic regression with a combination of under and oversampling on a full sample.  
